name: PR Check
on:
  pull_request:
    branches:
      - main
      - patch

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python syntax with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120

      - name: Check HTML syntax with htmlhint
        run: |
          npm install -g htmlhint
          htmlhint '**/*.html'

      - name: Check CSS syntax with stylelint
        run: |
          npm install -g stylelint
          stylelint '**/*.css'

      - name: Test Flask app running
        run: |
          export FLASK_APP=app.py  # Ganti dengan nama file Flask kamu
          export FLASK_ENV=development
          flask run &  # Menjalankan Flask di background
          sleep 5  # Tunggu beberapa detik agar Flask app bisa jalan
          curl --silent --fail http://127.0.0.1:5000/  # Mengakses halaman utama Flask
          
      - name: Check if Flask app is running
        run: |
          curl --silent --fail http://127.0.0.1:5000/ || exit 1  # Mengembalikan error jika halaman tidak dapat diakses